configuration: Release
platform: Any CPU
before_build:
    nuget restore Wlitsoft.Framework.Common.sln
test: off

artifacts:
  - path: '.nuget\Output\*.nupkg'
deploy:
- provider: NuGet
  api_key:
    secure: lhREP5b+1caZPUhktJQ1Brjj0SWjeF7sdP/NKK1PLnK1vt2zqTOkovA04fF19zZ/
  artifact: /.*\.nupkg/
  on:
    branch: dev-appveyor
